#OfflineManager 3.0 beta-0.1
#Created by flawe prod., LOVEC3327
#Contact https://vk.com/flawe0ff or https://t.me/flawe_sv
#Configuration file

#Set true if you want to enable only api. Commands will be disabled
only-api: false

placeholders: true

player-complete: true
command-complete: true

offline-inventory:
  enable: true
  interact: true
  name: "OfflineInventory"
offline-enderchest:
  enable: true
  interact: true
  name: "OfflineEnderChest"
offline-armor:
  enable: true
  interact: true
  name: "OfflineArmor"

#Commands settings
change-gamemode:
  enable: true
teleportation:
  enable: true
edit-location:
  enable: true
kill-player:
  enable: true
  clear-items: true
  drop-items: true
clear-inventory:
  enable: true
heal-player:
  enable: true
feed-player:
  enable: true